### ISSUE TITLE
Reason to keep __pycache__ in Git?

### ISSUE THREAD

**Issue by jermnelson** [KnowledgeLinks/kldgraph#7]
Should these [cache files](https://github.com/KnowledgeLinks/kldgraph/tree/master/kldgraph/__pycache__) be under source control? Running the tests locally generate new cache binaries as git changes to be commited.

**Comment by mstabile75** [comment]
I have these being removed in another branch and also added to .gitignore. These will disappear when that branch is merged

**Comment by mstabile75** [comment]
https://github.com/KnowledgeLinks/kldgraph/pull/8
removes the __pycache__ files
